---
style:
  tag:
    color: cyan
    width_percentage: 10
  comment:
    color: yellow
    width_percentage: 30
  snippet:
    color: white
    width_percentage: 50

finder:
  overrides: --height 20
  overrides_var: --height 20

cheats:
  paths:
    - ${HOME}/.config/navi/cheats
    - ${HOME}/.local/share/navi/cheats
